##### Get All Dish

GET localhost:8080/dish

##### Get Dish By Id

GET localhost:8080/dish/1

#### POST Dish

POST localhost:8080/dish
Content-Type: application/json

{
  "id": 5,
  "price": 15.6
}

#### DELETE Dish
DELETE localhost:8080/dish/1

